apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "revolut-devops-test.fullname" . }}
  labels:
    {{- include "revolut-devops-test.labels" . | nindent 4 }}
data:
  REVOLUT_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  REVOLUT_LOG_ENCODER: {{ .Values.config.logEncoder | quote }}
  REVOLUT_DATA_DIR: {{ .Values.config.dataDir | quote }}

