apiVersion: v1
kind: Service
metadata:
  name: {{ include "revolut-devops-test.fullname" . }}
  labels:
    {{- include "revolut-devops-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "revolut-devops-test.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "revolut-devops-test.fullname" . }}-health
  labels:
    {{- include "revolut-devops-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.healthService.type }}
  ports:
    - port: {{ .Values.healthService.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "revolut-devops-test.selectorLabels" . | nindent 4 }}
